 Пройдитесь по списку целых чисел. Замените числа, кратные 3, на "Fizz", кратные 5 на "Buzz", кратные обоим на "FizzBuzz". Остальные числа оставьте без изменений.

In [2]:
def listCheck (numbers):
  length = len(numbers)
  for i in range(0,length):
    if numbers[i] % 5 == 0 and numbers[i] % 3 == 0 :
      numbers[i] = "FizzBuzz"
    elif numbers[i] % 3 == 0:
      numbers[i] = "Fizz"
    elif numbers[i] % 5 == 0:
      numbers[i] = "Buzz"

  return numbers

In [3]:
testArray =[3,1,2,8,9,10,30,6,5]
print(listCheck(testArray))

['Fizz', 1, 2, 8, 'Fizz', 'Buzz', 'FizzBuzz', 'Fizz', 'Buzz']

Дан список температур. Найдите индексы начала и конца самой длинной непрерывной серии дней с температурой строго выше 0. Если таких дней нет, выведите -1 -1.

In [4]:
def findStreak(numbers):
  max_start = -1
  max_end = -1
  max_len = 0

  cur_start = -1
  cur_len = 0

  for i,temp in enumerate(numbers):
    if temp > 0:
      if cur_len ==0:
        cur_start = i
      cur_len = cur_len +1
    else:
      if cur_len > max_len:
        max_len = cur_len
        max_start = cur_start
        max_end = i - 1
      cur_len =0
  if max_len ==0:
    return -1,-1
  return max_start,max_end

In [6]:
temps=[-5,-2,1,3,5,-1,2,4,6,8,-3]
print(len(temps))
print(findStreak(temps))

11
(6, 9)

Дан список целых чисел. Создайте новый список, содержащий только уникальные элементы в порядке их первого появления. Не используйте встроенные методы.

In [8]:
def removeDup(numbers):
  result = []
  for number in numbers:
    isDuplicate = False
    for checkNumber in result:
      if checkNumber == number:
        isDuplicate=True
        break
    if not isDuplicate:
      result.append(number)
  return result

In [9]:
numbers=[9,1,2,6,1,5,9,5,5,6]
print(removeDup(numbers))

[9, 1, 2, 6, 5]

Дан список и число k. Сдвиньте все элементы списка вправо на k позиций. Элементы, выходящие за правый край, переносятся в начало. Реализуйте без готовых функций вроде rotate().

In [10]:
def arrShift(numbers, k):
  k = k % len(numbers)
  if k ==0:
    return numbers[:]

  return numbers[-k:] + numbers[:-k]

In [11]:
test=[1,2,3,4,5,6,7,8,9,10]
print(arrShift(test,2))

[9, 10, 1, 2, 3, 4, 5, 6, 7, 8]

Поиск локальных максимумов.Элемент списка считается локальным максимумом, если он строго больше обоих своих соседей. Первый и последний элементы не рассматриваются. Выведите сами пики и их индексы в исходном списке.

In [12]:
def findLocalPeak(numbers):
  peaks = []
  arrLength = len(numbers)
  for i in range (1,arrLength-1):
    if numbers[i] > numbers[i-1] and numbers[i]> numbers[i+1]:
      peaks.append([numbers[i],i])
  return peaks

In [13]:
peaksTest=[1,10,2,1,9,5,1,5,1,3,2]
print(findLocalPeak(peaksTest))

[[10, 1], [9, 4], [5, 7], [3, 9]]

Реализуйте иерархию классов для представления сотрудников в системе учета компании.

Базовый класс Employee:

	Конструктор должен принимать и сохранять основные данные: id, name, position (должность), base_salary (базовый оклад).

	Метод calculate_salary() возвращает итоговую зарплату. В базовой реализации это просто base_salary.

Дочерние классы:

	Manager: Помимо базового оклада, получает фиксированный бонус (bonus). Переопределите метод расчета зарплаты.

	Developer: Может иметь почасовую ставку (hourly_rate) и отработанные часы (hours_worked). ИЛИ получает бонус за завершенные проекты. Выберите одну схему и переопределите метод расчета зарплаты.

	(На ваше усмотрение) Придумайте и реализуйте еще один тип сотрудника .

Требования:

	Используйте наследование.

	В конструкторах дочерних классов обязательно применяйте super().

In [15]:
class Employee:
  def __init__(self, id,name,position,base_salary):
    self.id = id
    self.name = name
    self.position = position
    self.base_salary = base_salary

  def calculate_salary(self):
    return self.base_salary

In [16]:
class Manager(Employee):
  def __init__(self, id,name,position,base_salary,bonus):
    super().__init__(id,name,position,base_salary)
    self.bonus = bonus

  def calculate_salary(self):
    return self.base_salary + self.bonus

In [17]:
class Developer(Employee):
  def __init__(self, id,name,position,base_salary,hourly_rate,hours_worked):
    super().__init__(id,name,position,base_salary)
    self.hourly_rate = hourly_rate
    self.hours_worked = hours_worked

  def calculate_salary(self):
    return self.hourly_rate * self.hours_worked

In [20]:
class Intern(Employee):
  def __init__(self, id,name,position,base_salary,coeficent=0.5):
    super().__init__(id,name,position,base_salary)
    self.coeficent = coeficent

  def calculate_salary(self):
    return self.base_salary * self.coeficent

In [21]:
import pandas as pd
import numpy as np

data = {
    'student_id': range(1, 11),
    'name': ['Анна', 'Борис', 'Вика', 'Глеб', 'Даша', 'Егор', 'Женя', 'Зоя', 'Иван', 'Кира'],
    'group': ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'C'],
    'math_score': [85, 72, 90, np.nan, 65, 88, 78, 92, np.nan, 80],
    'physics_score': [70, 85, 95, 60, 75, 90, np.nan, 88, 70, 82],
    'attendance_rate': [0.95, 0.80, 0.98, 0.70, 0.85, 0.92, 0.75, 0.90, 0.88, 0.94]
}
df = pd.DataFrame(data)

Выведите первые 5 строк.

In [28]:
df.head(5)

   student_id   name group  math_score  physics_score  attendance_rate
0           1   Анна     A        85.0           70.0             0.95
1           2  Борис     B        72.0           85.0             0.80
2           3   Вика     A        90.0           95.0             0.98
3           4   Глеб     C         NaN           60.0             0.70
4           5   Даша     B        65.0           75.0             0.85

Определите размер таблицы (количество строк и столбцов).

In [30]:
print(df.shape)

(10, 6)

Выведите информацию о типах данных и наличии пропусков.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   student_id       10 non-null     int64
 1   name             10 non-null     object
 2   group            10 non-null     object
 3   math_score       8 non-null      float64
 4   physics_score    9 non-null      float64
 5   attendance_rate  10 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 612.0+ bytes

Получите статистическое описание числовых столбцов.

In [32]:
df.describe()

       student_id  math_score  physics_score  attendance_rate
count    10.00000    8.000000       9.000000        10.000000
mean      5.50000   81.250000      79.444444         0.867000
std       3.02765    9.361776      11.402972         0.091536
min       1.00000   65.000000      60.000000         0.700000
25%       3.25000   76.500000      70.000000         0.812500
50%       5.50000   82.500000      82.000000         0.890000
75%       7.75000   88.500000      88.000000         0.935000
max      10.00000   92.000000      95.000000         0.980000

Выберите всех студентов из группы 'B' с посещаемостью выше 0.85.
Для отфильтрованных студентов выведите только столбцы name и math_score.

In [38]:
filtered = df[(df['group']=="B") & (df['attendance_rate']>0.85)]

In [39]:
filtered[["name","math_score"]]

  name  math_score
7  Зоя        92.0

Заполните пропуски в math_score средним баллом по группе.
Создайте столбец total_score, равный сумме баллов по математике и физике.

In [41]:
df['math_score'] = df["math_score"].fillna(df.groupby("group")["math_score"].transform("mean"))

In [43]:
df['physics_score'] = df["physics_score"].fillna(df.groupby("group")["physics_score"].transform("mean"))

In [44]:
df["total_score"]= df["math_score"]+df["physics_score"]

In [45]:
df.head(5)

,student_id,name,group,math_score,physics_score,attendance_rate,total_score
0,1,Анна,A,85.0,70.0,0.95,155.0
1,2,Борис,B,72.0,85.0,0.80,157.0
2,3,Вика,A,90.0,95.0,0.98,185.0
3,4,Глеб,C,79.0,60.0,0.70,139.0
4,5,Даша,B,65.0,75.0,0.85,140.0

Сгруппируйте данные по столбцу group.
Для каждой группы вычислите: средний, минимальный и максимальный балл по математике и физике.

In [47]:
groupedInfo = df.groupby("group")[["math_score","physics_score"]].agg(["mean","max","min"])

In [48]:
groupedInfo

      math_score             physics_score
            mean   max   min          mean   max   min
group
A      87.666667  90.0  85.0     81.250000  95.0  70.0
B      76.333333  92.0  65.0     82.666667  88.0  75.0
C      79.000000  80.0  78.0     71.000000  82.0  60.0

Отсортируйте таблицу по total_score по убыванию.
Выберите топ-3 студентов с наибольшим суммарным баллом (игнорируя строки с NaN в total_score).

In [50]:
df.sort_values(by="total_score",ascending=False).head(3)

,student_id,name,group,math_score,physics_score,attendance_rate,total_score
2,3,Вика,A,90.0,95.0,0.98,185.0
7,8,Зоя,B,92.0,88.0,0.90,180.0
5,6,Егор,A,88.0,90.0,0.92,178.0